image: joni/openproject:latest
  
stages:
- trivy_fs_scan
- test
- owasp_dependency_scan
- build_docker
- sonarcloud_and_image_scan
- push_docker
- secert_detection

variables:
  NVD_API_KEY: 
  DOCKER_IMAGES: joni/openproject:latest/.docker.io
  MAVEN_OPTS: "-DskipTest=true"
  SONAR_HOST_URL: https://sonracloud.io
  SONAR_USER_HOME: "${CI_PROJSCT_DIR}/.sonar"
  GIT_DEPTH: '0'

 include:
 - template: Security/Secrt-Detection.gitlab-ci.yml
 - template: Security/SAST.gitlab-ci.yml

 cache:
   paths:
   - ".me/repositery"
   - ".sonar/cache"
   - dependency_check
   - "$CI_PROJECT_DIR/.trivy-db"
   key: "${CI_COMMIT_RFE_SLUG}"

trivy_fs_scan:
  stage: trivy_fs_scan
  image: alpine:latest
  rules:
  - changes:
    - ".gitlab-ci.yml"
    - Dockerfile
    - src/**
  before_script:
   - apk add --no-cache bash curl
   - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh
    | sh -s -- -b /usr/local/bin

  script:
  - export TRIVY_CHCHE_DRI=$CI_PROJECT_DIR/.trivy-db
  - trivy fs --cachedir $TRIVY_CACHE_DIR .


owasp_scan:
 stage: owasp_dependency_scan
 image: owasp/dependency-check
 rules:
 - changes:
   - ".gitlab-ci.yml"
   - pom.xml
   - src/**
 before_script:
  - mkdir -p data dependency-check
 script:
  - /user/share/dependency-check/bin/dependency-check.sh --project Test -out dependency-check
   --scan . enableExperimental --nvDApiKey "$NVD_API_KEY"
 artifacts:
   paths:
    - dependency-check
 allow_failure: true


build_docker:
  stage: build_docker
  image: Docker:latest
  services:
   - docker.dind
  rules:
    - changes: 
      - ".gitlab-ci.yml"
      - Dockerfile
      - docker/**
  script:
    - docker build -t $DOCKER_IMAGES .
    - docker save $DOCKER_IMAGES > docker_images.tar
  artifacts:
    paths:
     - docker_images.tar
    expire_in: 30 days

sonarcloud_and_image_scan:
  stage: sonarcloud_and_image_scan
  image: sonarsource/sonar-scanner-cli:latest
  cache:
   paths:
     - ".sonar/cache"
  rules:
    - changes: 
      - ".gitlab-ci.yml"
      - src/**
  script:
   - sonar-scannar

trivy_image_scan:
  stage: sonarcloud_and_image_scan
  image: docker:24.dind
  services:
   - docker:24.dind
  rules:
  - changes:
    - ".gitlab-ci.yml"
    - Dockerfile 
    - src/**
  before_script:
    - apk add --no-cache bash curl
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh
     | sh -s -- -b /usr/local/bin

  script:
    - docker load -i docker_image.tar || echo "no valide docker image tar "
    - trivy image scan $DOCKER_IMAGE --scanner vuln --exit-code 0 --no-progres --formate 
      json --output "$CI_PROJSCT_DIR/gl-container-scanning.json"
  artifacts:
    reports:
       container_scanning: gi-continer-scanning
       path:
        - gi-container-scanning

secret_detection:
  stage: secret_detection 
  rules:
   - changes:
     - ".gitlab-ci.yml"
     - src/**
  script:
   - echo "testing the job build"


push_docker:
  stage: push_docker
  image: Docker:latest
  services:
    - docker:dind
  rules:
    - changes: 
     - ".gitlab-ci.yml"
     - docker/**
  before_script:
   - echo "$DOCKE_PASSWORD " | docker login  --username "$DCOKER_USER" --password-stdin
  script:
   - docker load docker_image.tar
   - docker push $DOCKER_IMAGE
  dependencies:
    - build_docker

sast:
 stage: test
 rules:
   - changes: 
     - ".gitlab-ci.yml"
     -  src/**
 script:
   - echo "running SAST analysis"







     



    










 

 



     



    




